import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import WrappedLink from '@/components/WrappedLink';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const sidebarLinks = [
  {
    href: '/',
    label: 'Home',
  },
  {
    href: '/blog',
    label: 'Blog',
  },
  {
    href: 'https://github.com/CodeByCorey',
    label: 'GitHub',
  },
  {
    href: 'https://www.linkedin.com/in/CodeByCorey',
    label: 'LinkedIn',
  },
  {
    href: 'https://twitter.com/horticoder',
    label: 'Twitter',
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/static/favicon/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/static/favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/static/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/static/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/static/favicon/site.webmanifest" />
        <meta name="monetization" content="$ilp.uphold.com/GAK9Q8Wb6Q9A"></meta>
      </head>
      <body className={inter.className}>
        <main className="flex flex-wrap justify-center max-w-5xl mx-auto">
          <div className="grow-1 px-8">
            <div className="space-y-5 flex flex-col items-center mt-12 sticky top-12">
              <Image
                alt="profile"
                src="/static/images/profile.jpg"
                width="200"
                height="200"
                className="rounded-full mb-4"
              />
              <div className="space-y-5">
                <h1 className="text-4xl">{"Corey O'Donnell"}</h1>
                <h2 className="text-2xl">Software Engineer</h2>
                <nav>
                  <ul className="space-y-2">
                    {sidebarLinks.map((link) => (
                      <li key={link.href}>
                        <WrappedLink className="text-xl" href={link.href}>
                          {link.label}
                        </WrappedLink>
                      </li>
                    ))}
                  </ul>
                </nav>
              </div>
            </div>
          </div>
          <div className="basis-0 grow-[999] min-w-[50%]">{children}</div>
        </main>
      </body>
    </html>
  );
}
