import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/Sidebar';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <main className="flex flex-wrap justify-center max-w-5xl mx-auto">
          <div className="grow-1 px-8">
            <Sidebar />
          </div>
          <div className="basis-0 grow-[999] min-w-[50%]">{children}</div>
        </main>
      </body>
    </html>
  );
}
